In [1]:
import numpy as np

In [2]:
vec = [1, 2, 3, 4]

vec = np.array(vec)

print(f'{vec}\n{type(vec)}')

[1 2 3 4]
<class 'numpy.ndarray'>


#### shape of matrix

In [3]:
print(vec.shape)

(4,)


In [4]:
vec_2 = np.array([
                 [1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]
                 ])

print(f'{vec_2}\n{vec_2.shape}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


#### shapes


- scalar 0-D ==> is a single number
- vector 1-D ==> a single row of numbers with 2 or more columns
- matrices 2-D ==> it has some rows and some columns
- tensor 3-D ==> each row of bigger matrice has another matrice in itself

In [5]:
tens = [
        [[1, 2, 3, 0], [3, 2, 1, 0], [2, 1, 3, 0]],
        [[4, 4, 5, 8], [5, 8, 5, 4], [5, 6, 4, 5]]
       ]

In [6]:
tens = np.array(tens)
tens.shape

(2, 3, 4)

#### np.resize()

In [7]:
a = np.array([[1, 2], [3, 4]])

a = np.resize(a, (3, 5))

print(a)

[[1 2 3 4 1]
 [2 3 4 1 2]
 [3 4 1 2 3]]


In [8]:
a = np.array([[1, 2], [3, 4]])

a = np.resize(a, (3, 4, 2))

print(a)

[[[1 2]
  [3 4]
  [1 2]
  [3 4]]

 [[1 2]
  [3 4]
  [1 2]
  [3 4]]

 [[1 2]
  [3 4]
  [1 2]
  [3 4]]]


#### zeros and ones

In [9]:
vec = np.ones((2,3), dtype=str)

print(vec)

[['1' '1' '1']
 ['1' '1' '1']]


In [10]:
vec = np.ones((2,3), dtype=complex)

print(vec)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [11]:
vec = np.zeros((1,2,3), dtype=int)

print(vec)

[[[0 0 0]
  [0 0 0]]]


#### vertical stack

column of arrays should be same size

In [12]:
m1 = np.zeros((2,3), int)

m2 = np.ones((4,3), str)

print(f"{m1}\n\n{m2}")

[[0 0 0]
 [0 0 0]]

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [13]:
np.vstack((m1,m2))

array([['0', '0', '0'],
       ['0', '0', '0'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U21')

#### horizontal stack

row of arrays should be same size

In [14]:
m1 = np.zeros((3,1), int)

m2 = np.ones((3, 3))

print(f"{m1}\n\n{m2}")

[[0]
 [0]
 [0]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
np.hstack((m2,m1))

array([[1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.]])

#### dot product

In [16]:
a = np.array([1, 2, 3])
b = np.array([10, 15, 25])

np.dot(a, b )

115

In [17]:
a = np.array([1, 2, 3])
b = np.array([10, 15, 25])

a.dot(b)

115

#### trace of matrices

In [18]:
mat = np.array([[4, 5, 6, 7], [1, 2, 3, 9]])

traceMat = mat.T
print(f'{mat}\n\n{traceMat}')

[[4 5 6 7]
 [1 2 3 9]]

[[4 1]
 [5 2]
 [6 3]
 [7 9]]


#### astype()

changes the type of matrices

In [19]:
mat = np.array([[4, 5, 6, 7], [1, 2, 3, 9]])

mat_2 = mat.astype("float")

print(mat_2)

[[4. 5. 6. 7.]
 [1. 2. 3. 9.]]


#### mathematical

- sum()
- min()
- max()
- argmin()  ==> index of min item in matrix
- argmax()  ==> index of max item in matrix
- mean()

In [20]:
mat = np.array([[1, 2], [3, 4], [5, 5]])

summ = mat.sum()

maxx = mat.max()

minn = mat.min()

armin = mat.argmin()

armax = mat.argmax()

meann = mat.mean()

stdd = mat.std()

print(f"""
      'sum :'{summ}\n\n
      'max :'{maxx}\n\n
      'min :'{minn}\n\n
      'argmin :'{armin}\n\n
      'argmax :'{armax}\n\n
      'mean :'{meann}\n\n
      'std :'{stdd}""")


      'sum :'20


      'max :'5


      'min :'1


      'argmin :'0


      'argmax :'4


      'mean :'3.3333333333333335


      'std :'1.4907119849998598


#### slicing

In [21]:
mat = np.arange(8)
mat

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
mat[2:5]

array([2, 3, 4])

In [23]:
mat = np.array([[1, 2, 7], [3, 4, 10], [5, 6, 17]])
mat

array([[ 1,  2,  7],
       [ 3,  4, 10],
       [ 5,  6, 17]])

In [24]:
mat[1:, 1:]

array([[ 4, 10],
       [ 6, 17]])

### advanced

In [25]:
mat = [[0, 2, 5], [2, 4, 9], [5.6, 7, 4]]

mat = np.array(mat)

mat

array([[0. , 2. , 5. ],
       [2. , 4. , 9. ],
       [5.6, 7. , 4. ]])

In [26]:
mat[mat >= 5]

array([5. , 9. , 5.6, 7. ])

In [27]:
mat >= 5

array([[False, False,  True],
       [False, False,  True],
       [ True,  True, False]])